Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2018-10, with the labels that each got.

#482 CT-1956 Make Human readable corr type on mails
  app/mailers/action_notifications_mailer.rb
  spec/mailers/action_notifications_mailer_spec.rb
Labels: Ready for Peer Review

#483 CT-1901 create ico overturned foi
  app/controllers/assignments_controller.rb
  app/controllers/cases_controller.rb
  app/controllers/concerns/overturned_ico_params.rb
  app/models/case/base.rb
  app/models/case/overturned_ico/base.rb
  app/models/case/overturned_ico/foi.rb
  app/models/case/overturned_ico/sar.rb
  app/services/case_create_service.rb
  app/services/new_overturned_ico_case_service.rb
  app/views/cases/overturned_shared/_new.html.slim
  app/views/cases/overturned_shared/_new_form.html.slim
  config/locales/en.yml
  spec/controllers/cases_controller/create_spec.rb
  spec/controllers/cases_controller/show_spec.rb
  spec/features/cases/overturned_sar/create_case_spec.rb
  spec/features/user_journeys/overturned_foi/non_trigger_spec.rb
  spec/features/user_journeys/overturned_sar/non_trigger_spec.rb
  spec/models/case/base_spec.rb
  spec/models/case/overturned_ico/foi_spec.rb
  spec/models/case/overturned_ico/sar_spec.rb
  spec/rails_helper.rb
  spec/services/case_create_service_spec.rb
  spec/services/new_overturned_ico_case_service_spec.rb
  spec/site_prism/page_objects/pages/application.rb
  spec/site_prism/page_objects/pages/cases/new/overturned_ico_page.rb
  spec/site_prism/page_objects/sections/cases/overturned_foi/show_section.rb
  spec/site_prism/page_objects/sections/cases/overturned_ico/new_form_section.rb
  spec/site_prism/page_objects/sections/cases/overturned_sar/form_section.rb
  spec/site_prism/page_objects/sections/shared/gov_uk_date_section.rb
  spec/support/features/interactions.rb
  spec/support/features/interactions/overturned_ico.rb
  spec/support/features/interactions/overturned_sar.rb
  spec/support/features/steps/cases/create_steps.rb
  spec/support/matchers/require_permission.rb
  spec/support/stub_policy.rb
  spec/views/assignments/edit_page_spec.rb
  spec/views/cases/_case_request_html_slim_spec.rb
  spec/views/cases/_clearance_levels_html_slim_spec.rb
  spec/views/cases/ico/_ico_final_decision_html_slim_spec.rb
  spec/views/cases/overturned_shared/new_html_slim_spec.rb
Labels: Ready for Peer Review

#481 CT-1937 Fix Case Linking bug
  app/services/case_linking_service.rb
  spec/services/case_linking_service_spec.rb
Labels: Ready for Peer Review

#500 CT-1958 Enable ICO Overturn FOI for staging
  config/settings.yml
Labels: Ready for Peer Review

#504 CT-1967 add factories for trigger ICO Overturned FOIs cases
  spec/factories/business_units.rb
  spec/factories/case/fois.rb
  spec/factories/case/overturned_ico_fois.rb
  spec/factories/case_transitions.rb
  spec/factory_specs/overturned_ico_foi_factory_spec.rb
Labels: Ready for Peer Review

#503 CT-1969 Create trigger overturned FOI
  app/controllers/concerns/overturned_ico_params.rb
  app/decorators/case/overturned_ico/foi_decorator.rb
  app/helpers/application_helper.rb
  app/models/case/overturned_ico/foi.rb
  app/services/new_overturned_ico_case_service.rb
  app/views/cases/overturned_shared/_new.html.slim
  config/settings.yml
  spec/controllers/cases_controller/create_spec.rb
  spec/features/cases/overturned_sar/create_case_spec.rb
  spec/models/case/overturned_ico/foi_spec.rb
  spec/services/case_create_service_spec.rb
  spec/site_prism/page_objects/pages/cases/new/overturned_ico_page.rb
  spec/site_prism/page_objects/sections/cases/overturned_ico/new_form_section.rb
  spec/views/cases/new_html_slim_spec.rb
  spec/views/cases/overturned_shared/new_html_slim_spec.rb
Labels: Ready for Peer Review

#516 CT-1970 add filter for ICO overturned cases
  app/models/case/base.rb
  app/services/case_type_filter.rb
  config/locales/filters.en.yml
  spec/features/cases/list_filter_journey_spec.rb
  spec/models/case/base_spec.rb
  spec/services/case_type_filter_spec.rb
  spec/site_prism/page_objects/sections/cases/type_filter_panel_section.rb
  spec/support/standard_setup.rb
Labels: Ready for Peer Review

#523 CT-1985 extend for pit feature test ot foi
  spec/features/user_journeys/overturned_foi/ovt_foi_non_trigger_e2e_spec.rb
  spec/features/user_journeys/overturned_foi/ovt_foi_trigger_e2e_spec.rb
Labels: 1st Up

#525 CT-1986 allow responders to edit sar closure details
  app/controllers/cases_controller.rb
  app/services/update_closure_service.rb
  config/state_machine/configs/00_moj/20_sar/30_sar_trigger_workflow.yml
  spec/controllers/cases_controller/update_closure_spec.rb
  spec/services/update_closure_service_spec.rb
Labels: Ready for Peer Review

#534 CT-2012-enable-trigger-ot-fois-demo-staging-prod
  config/settings.yml
  spec/features/user_journeys/overturned_foi/ovt_foi_trigger_e2e_spec.rb
Labels: ready to merge

#541 CT-1989 allow ot sar to be trigger
  config/settings.yml
  spec/features/cases/overturned_sar/assigning_spec.rb
  spec/features/cases/overturned_sar/create_case_spec.rb
  spec/features/user_journeys/overturned_sar/trigger_spec.rb
  spec/site_prism/page_objects/sections/cases/overturned_ico/new_form_section.rb
  spec/support/features/interactions/overturned_ico.rb
  spec/support/features/steps/cases/create_steps.rb
Labels: ready to merge

#533 CT-1964 add sar tmm refusal reason
  app/controllers/cases_controller.rb
  app/models/case_closure/refusal_reason.rb
  db/data_migrations/20181023094940_create_and_populate_sar_tmm_closure_reason.rb
  db/seeders/case_closure_metadata_seeder.rb
  spec/controllers/cases_controller/close_spec.rb
  spec/controllers/cases_controller/update_closure_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/factories/case_closure_metadata.rb
  spec/support/features/steps/cases/edit_steps.rb
  spec/support/features/steps/cases/responding_steps.rb
Labels: Ready for Peer Review

#536 CT2015-wip
  spec/decorators/case_transition_decorator_spec.rb
  spec/factories/case/fois.rb
  spec/factories/case/ico_fois.rb
  spec/factories/case/ico_sars.rb
  spec/factories/case/overturned_ico_sars.rb
  spec/factories/case_transitions.rb
  spec/factory_specs/ico_factory_spec.rb
  spec/factory_specs/overturned_ico_sar_factory_spec.rb
  spec/state_machines/workflows/foi_permitted_events/trigger_spec.rb
  spec/state_machines/workflows/ico_permitted_events_spec/ico_appeal_trigger_spec.rb
  spec/state_machines/workflows/overturned_foi_permitted_events/full_approval_spec.rb
Labels: Ready for Peer Review

#545 Ct 1992 accept reject ot trigger sar
  spec/features/user_journeys/overturned_sar/trigger_spec.rb
Labels: 1st Up, ready to merge

#544 Ct 1994 progress to disclosure
  spec/features/user_journeys/overturned_sar/trigger_spec.rb
Labels: 2nd Up, ready to merge

#547 CT-2018 prepopulate radio buttons on the edit closure details page
  app/decorators/case/overturned_ico/sar_decorator.rb
  app/decorators/case/sar_decorator.rb
Labels: 3rd Up, ready to merge

#554 CT-2002 add ot sar disclousre approval feature test
  config/locales/en.yml
  spec/features/user_journeys/overturned_sar/trigger_spec.rb
Labels: Ready for Peer Review

#556 CT-1998 add close ot trigger sar feature test
  spec/features/user_journeys/overturned_sar/trigger_spec.rb
Labels: Ready for Peer Review

#557 CT-1994 add notification for progress to disclosure allow anyone in responding team to progress
  app/controllers/cases_controller.rb
  app/state_machines/workflows/hooks.rb
  config/state_machine/configs/00_moj/20_sar/30_sar_trigger_workflow.yml
  spec/controllers/cases_controller/progress_for_clearance_spec.rb
  spec/state_machines/sar_event_spec.rb
  spec/state_machines/workflows/hooks_spec.rb
Labels: Ready for Peer Review
