Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2018-07, with the labels that each got.

#306 CT-1327 specs and other tidying up for create ICO page
  app/controllers/admin/cases_controller.rb
  app/controllers/cases_controller.rb
  app/controllers/concerns/foi_cases_params.rb
  app/controllers/concerns/sar_cases_params.rb
  app/policies/case/base_policy.rb
  app/policies/case/ico/base_policy.rb
  app/policies/case/ico/foi_policy.rb
  app/policies/case/ico/sar_policy.rb
  app/services/get_case_class_from_params_service.rb
  app/views/admin/cases/foi/_new.html.slim
  app/views/admin/cases/sar/_new.html.slim
  app/views/cases/foi/_edit.html.slim
  app/views/cases/foi/_new.html.slim
  app/views/cases/ico/_new.html.slim
  app/views/cases/sar/_edit.html.slim
  app/views/cases/sar/_new.html.slim
  lib/host_env.rb
  spec/controllers/cases_controller/create_spec.rb
  spec/controllers/cases_controller/permitted_correspondence_types_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/lib/host_env_spec.rb
  spec/models/case/ico/base_spec.rb
  spec/models/case/ico/foi_spec.rb
  spec/models/case/ico/sar_spec.rb
  spec/models/correspondence_type_spec.rb
  spec/models/user_spec.rb
  spec/policies/cases/ico/foi_policy_spec.rb
  spec/policies/cases/ico/sar_policy_spec.rb
  spec/services/case_create_service_spec.rb
  spec/services/get_case_class_from_params_service_spec.rb
  spec/support/feature_sets.rb
  spec/support/standard_setup.rb
  spec/views/cases/edit_html_slim_spec.rb
Labels: 1st Up!, Ready for Peer Review

#319 CT-1817 remove 'remove clearance' link for icos
  app/helpers/cases_helper.rb
  app/policies/case/ico/base_policy.rb
  spec/views/cases/_clearance_levels_html_slim_spec.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: 1st Up!

#317 CT-1823 ico approval journey
  spec/features/cases/foi/case_approvals/disclosure_specialist_approval_spec.rb
  spec/features/cases/ico/ico_approval.rb
  spec/features/cases/ico/ico_approval_spec.rb
  spec/features/user_journeys/ico/trigger_e2e_journey.rb
  spec/support/features/interactions.rb
  spec/support/features/steps/cases/taking_on_and_escalating_case_steps.rb
Labels: 1st Up!

#316 CT-1782 add tests for deleting an ICO case
  spec/controllers/cases_controller/destroy_spec.rb
  spec/features/cases/ico/delete_ico_spec.rb
  spec/features/cases/sar/case_deleting_spec.rb
Labels: 1st Up!

#322 Ct 1802 sar appeals report
  app/services/stats/r102_sar_appeals_performance_report.rb
  db/migrate/20180716150951_add_sar_appeals_report.rb
  db/seeders/report_type_seeder.rb
  db/structure.sql
  spec/features/user_journeys/foi/downloading_stats_spec.rb
  spec/services/stats/r102_sar_appeals_performance_report_spec.rb
Labels: Ready for Peer Review

#323 Ct 1800 ready to send to ico state
  app/decorators/case/base_decorator.rb
  app/services/current_team_and_user/ico/trigger.rb
  app/views/cases/index.html.slim
  app/views/cases/shared/_case_list.html.slim
  config/i18n-tasks.yml
  config/locales/en.yml
  config/state_machine/configs/00_moj/30_ico/10_ico_preamble.yml
  config/state_machine/configs/00_moj/30_ico/20_ico_trigger_workflow.yml
  config/state_machine/moj.yml
  spec/decorators/case/base_decorator_spec.rb
  spec/factories/case/ico_fois.rb
  spec/factory_specs/ico_factory_spec.rb
  spec/features/cases/ico/ico_approval_spec.rb
  spec/features/user_journeys/ico/trigger_e2e_journey.rb
Labels: Ready for Peer Review

#311 CT-1776 add case link to ico
  app/assets/javascripts/modules/CaseCreation.js
  app/controllers/cases_controller.rb
  app/controllers/concerns/ico_cases_params.rb
  app/decorators/case/ico/base_decorator.rb
  app/decorators/case/ico/foi_decorator.rb
  app/decorators/case/ico/sar_decorator.rb
  app/models/case/base.rb
  app/models/case/ico/base.rb
  app/models/linked_case.rb
  app/models/report_type.rb
  app/services/case_linking_service.rb
  app/services/get_case_class_from_params_service.rb
  app/validators/case_link_type_validator.rb
  app/views/cases/ico/_new_form.html.slim
  app/views/cases/ico/case_linking/_linked_cases.html.slim
  app/views/cases/ico/case_linking/_new_case_link_form.html.slim
  app/views/cases/new.html.slim
  config/locales/en.yml
  config/routes.rb
  db/migrate/20180711151118_add_type_column_to_linked_cases.rb
  db/structure.sql
  spec/controllers/cases_controller/create_spec.rb
  spec/controllers/cases_controller/new_linked_cases_for_spec.rb
  spec/decorators/case/ico/base_decorator_spec.rb
  spec/decorators/case/ico/foi_decorator_spec.rb
  spec/decorators/case/ico/sar_decorator_spec.rb
  spec/factories/case/ico_fois.rb
  spec/factories/case/ico_sars.rb
  spec/factories/report_types.rb
  spec/features/cases/ico/case_creating/creating_spec.rb
  spec/features/user_journeys/ico/trigger_e2e_journey.rb
  spec/models/case/base_spec.rb
  spec/models/case/ico/base_spec.rb
  spec/models/linked_case_spec.rb
  spec/models/report_type_spec.rb
  spec/policies/base_policy_scope_spec.rb
  spec/policies/cases/sar_policy_spec.rb
  spec/rails_helper.rb
  spec/services/case_create_service_spec.rb
  spec/services/case_linking_service_spec.rb
  spec/services/case_type_filter_spec.rb
  spec/services/get_case_class_from_params_service_spec.rb
  spec/site_prism/page_objects/pages/cases/new/ico_page.rb
  spec/site_prism/page_objects/pages/cases/remove_clearance_form_page.rb
  spec/support/features/interactions.rb
  spec/support/features/steps/cases/create_steps.rb
  spec/validators/case_link_type_validator_spec.rb
  spec/views/cases/ico/_new_html_slim_spec.rb
  spec/views/cases/new_case_link_html_slim_spec.rb
  spec/views/cases/new_html_slim_spec.rb
Labels: Ready for Peer Review

#332 CT-1776 fix error message when cross-linking FOI / SAR cases
  app/controllers/concerns/ico_cases_params.rb
  app/helpers/cases_helper.rb
  config/locales/en.yml
  spec/controllers/cases_controller/new_linked_cases_for_spec.rb
Labels: 1st Up!
