Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2018-11, with the labels that each got.

#558 Ct 2017 upload response awaiting dispatch trigger
  app/controllers/cases_controller.rb
  app/policies/case/base_policy.rb
  app/services/response_uploader_service.rb
  app/views/cases/show.html.slim
  config/state_machine/configs/00_moj/10_foi_case_type/20_foi_standard_workflow.yml
  config/state_machine/configs/00_moj/10_foi_case_type/30_foi_trigger_workflow.yml
  config/state_machine/configs/00_moj/10_foi_case_type/40_foi_full_approval_workflow.yml
  config/state_machine/configs/00_moj/30_ico/20_ico_trigger_workflow.yml
  lib/cts/cases/create.rb
  lib/cts/demo_setup.rb
  spec/controllers/cases_controller/show_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/factories/case_transitions.rb
  spec/factory_specs/overturned_ico_foi_factory_spec.rb
  spec/models/case/base_spec.rb
  spec/models/case/foi/standard_spec.rb
  spec/policies/cases/base_policy_spec.rb
  spec/services/response_uploader_service_spec.rb
  spec/state_machines/foi_event_spec.rb
  spec/state_machines/ico_event_spec.rb
  spec/state_machines/workflows/foi_permitted_events/full_approval_spec.rb
  spec/state_machines/workflows/foi_permitted_events/trigger_spec.rb
  spec/state_machines/workflows/ico_permitted_events_spec/ico_appeal_trigger_spec.rb
  spec/state_machines/workflows/overturned_foi_permitted_events/full_approval_spec.rb
  spec/state_machines/workflows/overturned_foi_permitted_events/trigger_spec.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: ready to merge

#555 CT-1990 Re-assign Trigger OVT SAR case to a new team
  spec/controllers/assignments_controller/assignments_controller_spec.rb
  spec/state_machines/overturned_sar_event_spec.rb
  spec/support/standard_setup.rb
Labels: ready to merge

#559 ct-2020 hide update closure on trigger ot sar
  app/controllers/feedback_controller.rb
  app/state_machines/workflows/predicates.rb
  config/settings.yml
  config/state_machine/configs/00_moj/20_sar/20_sar_standard_workflow.yml
  config/state_machine/configs/00_moj/20_sar/30_sar_trigger_workflow.yml
Labels: ready to merge

#564 Ct 2019 release ot trigger sar
  config/settings.yml
  spec/factories/case/overturned_ico_sars.rb
  spec/state_machines/overturned_sar_event_spec.rb
  spec/state_machines/workflows/overturned_sar_permitted_events/trigger_spec.rb
Labels: Ready to merge

#570 Ct 2023 deactivate directorates
  app/controllers/teams_controller.rb
  app/helpers/teams_helper.rb
  app/models/business_unit.rb
  app/models/team.rb
  app/policies/team_policy.rb
  app/views/teams/_business_unit_detail.html.slim
  app/views/teams/_directorate_detail.html.slim
  config/i18n-tasks.yml
  config/locales/en.yml
  spec/controllers/teams_controller/destroy_spec.rb
  spec/features/admin/deactivating_teams_spec.rb
  spec/helpers/teams_helper_spec.rb
  spec/views/teams/show_html_slim_spec.rb
Labels: Ready for Peer Review

#576 CT-2023 update flash message when deactivating teams
  app/controllers/teams_controller.rb
  app/models/team.rb
  config/locales/en.yml
  spec/controllers/teams_controller/destroy_spec.rb
  spec/features/admin/deactivating_teams_spec.rb
  spec/models/team_spec.rb
Labels: Ready for Peer Review

#584 CT-2023 downcase team type
  app/controllers/teams_controller.rb
  spec/controllers/teams_controller/destroy_spec.rb
  spec/features/admin/deactivating_teams_spec.rb
Labels: Ready for Peer Review

#575 Ct 2024 remove pit extension
  app/controllers/cases_controller.rb
  app/helpers/cases_helper.rb
  app/models/case/base.rb
  app/models/case_transition.rb
  app/policies/case/base_policy.rb
  app/services/case_extend_for_pit_service.rb
  app/services/case_remove_pit_extension_service.rb
  app/state_machines/workflows/predicates.rb
  app/views/cases/show.html.slim
  config/locales/en.yml
  config/locales/event.en.yml
  config/routes.rb
  config/state_machine/configs/00_moj/10_foi_case_type/20_foi_standard_workflow.yml
  config/state_machine/configs/00_moj/10_foi_case_type/30_foi_trigger_workflow.yml
  config/state_machine/configs/00_moj/10_foi_case_type/40_foi_full_approval_workflow.yml
  db/data_migrations/20181108165032_add_original_date_to_extend_for_pit.rb
  spec/factories/case/fois.rb
  spec/factories/case_transitions.rb
  spec/models/case/base_spec.rb
  spec/services/case_extend_for_pit_service_spec.rb
  spec/services/case_remove_pit_extension_service_spec.rb
  spec/site_prism/page_objects/pages/cases/show_page.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: Ready for Peer Review

#585 CT-2021 Truncate and remove quotes from message field
  app/services/csv_exporter.rb
  db/structure.sql
Labels: Ready for Peer Review

#574 CT-2025 List cases by user
  app/controllers/application_controller.rb
  app/controllers/cases_controller.rb
  app/controllers/teams_controller.rb
  app/controllers/users_controller.rb
  app/services/user_active_case_count_service.rb
  app/views/teams/_business_unit_detail.html.slim
  app/views/users/show.html.slim
  config/i18n-tasks.yml
  config/locales/en.yml
  config/routes.rb
  spec/controllers/teams_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/features/admin/deactivating_users_spec.rb
  spec/services/user_active_case_count_service_spec.rb
  spec/site_prism/page_objects/pages/application.rb
  spec/site_prism/page_objects/pages/teams/show_page.rb
  spec/site_prism/page_objects/pages/users/edit_page.rb
  spec/site_prism/page_objects/pages/users/show_page.rb
  spec/views/teams/show_html_slim_spec.rb
  spec/views/users/show_html_slim_spec.rb
Labels: Ready for Peer Review

#597 CT-2040 Update Installation instructions in README
  README.md
  run.sh
Labels: Ready for Peer Review
