Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2018-09, with the labels that each got.

#410 Ct 1813 create overturned button
  app/decorators/case/sar_decorator.rb
  app/helpers/cases_helper.rb
  app/state_machines/workflows/predicates.rb
  app/views/cases/show.html.slim
  config/locales/en.yml
  config/state_machine/configs/00_moj/30_ico/20_ico_trigger_workflow.yml
  config/state_machine/moj.yml
  spec/factories/case/ico_sars.rb
  spec/site_prism/page_objects/pages/cases/show_page.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: Ready for Peer Review

#419 CT-1847 Update visibility of Overturned SAR cases
  .gitignore
  app/models/case/base.rb
  app/models/case/ico/base.rb
  app/models/case/overturned_ico/base.rb
  app/policies/case/base_policy.rb
  app/services/global_nav_manager/page.rb
  config/state_machine/moj.yml
  spec/factories/case/overturned_icos.rb
  spec/services/case_finder_service_spec.rb
Labels: Ready for Peer Review

#396 CT-1891 Update case details page display once ICO case has been closed
  app/decorators/case/base_decorator.rb
  app/decorators/case/ico/base_decorator.rb
  app/decorators/case/ico/foi_decorator.rb
  app/decorators/case/ico/sar_decorator.rb
  app/views/cases/ico/_ico_final_decision.html.slim
  app/views/cases/shared/_closed_case_details.html.slim
  app/views/cases/show.html.slim
  config/locales/en.yml
  config/locales/state.en.yml
  lib/cts/cases/create.rb
  spec/decorators/case/base_decorator_spec.rb
  spec/decorators/case/ico/base_decorator_spec.rb
  spec/decorators/case/ico/foi_decorator_spec.rb
  spec/decorators/case/ico/sar_decorator_spec.rb
  spec/factories/case/ico_fois.rb
  spec/factories/case/ico_sars.rb
  spec/views/cases/ico/_case_details_html_slim_spec.rb
  spec/views/cases/ico/edit_html_slim_spec.rb
  spec/views/cases/respond_html_slim_spec.rb
Labels: Ready for Peer Review

#416 ct-1849 add message to overturned sar
  spec/controllers/messages_controller_spec.rb
  spec/features/user_journeys/overturned_sar/non_trigger_spec.rb
  spec/support/features/interactions.rb
  spec/support/features/steps/cases/create_steps.rb
Labels: ready to merge

#420 Ct 1875 request further clearance on sars
  app/policies/case/sar_policy.rb
  app/services/request_further_clearance_service.rb
  config/state_machine/configs/00_moj/20_sar/20_sar_standard_workflow.yml
  config/state_machine/configs/00_moj/20_sar/30_sar_trigger_workflow.yml
  config/state_machine/moj.yml
  spec/controllers/cases_controller/request_further_clearance_spec.rb
  spec/services/request_further_clearance_service_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_standard_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_trigger_spec.rb
Labels: 1st Up, ready to merge

#417 Ct 1876 non trigger extend for pit
  app/policies/case/base_policy.rb
  app/services/case_extend_for_pit_service.rb
  config/state_machine/configs/00_moj/10_foi_case_type/20_foi_standard_workflow.yml
  config/state_machine/configs/00_moj/10_foi_case_type/30_foi_trigger_workflow.yml
  config/state_machine/configs/00_moj/10_foi_case_type/40_foi_full_approval_workflow.yml
  config/state_machine/moj.yml
  spec/controllers/cases_controller/execute_extend_for_pit_spec.rb
  spec/controllers/cases_controller/extend_for_pit_spec.rb
  spec/features/cases/foi/case_extend_for_pit_spec.rb
  spec/features/user_journeys/foi/compliance_review_trigger_e2e_spec.rb
  spec/features/user_journeys/foi/trigger_e2e_spec.rb
  spec/policies/cases/base_policy_spec.rb
  spec/services/case_extend_for_pit_service_spec.rb
  spec/state_machines/foi_event_spec.rb
  spec/state_machines/workflows/foi_permitted_events/full_approval_spec.rb
  spec/state_machines/workflows/foi_permitted_events/standard_spec.rb
  spec/state_machines/workflows/foi_permitted_events/trigger_spec.rb
Labels: 1st Up, ready to merge

#421 CT-1881 - Make ICO decision file mandatory when closing a case
  README.md
  app/validators/closed_case_validator.rb
  app/views/cases/show.html.slim
  config/locales/en.yml
  spec/factories/case/ico_fois.rb
  spec/factories/case/ico_sars.rb
  spec/features/user_journeys/overturned_sar/non_trigger_spec.rb
  spec/services/case_finder_service_spec.rb
  spec/site_prism/page_objects/sections/cases/ico/closure_section.rb
  spec/support/features/steps/cases/responding_steps.rb
  spec/validators/closed_case_validator_spec.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: Ready for Peer Review

#423 CT-1912 Allow SAR and ICO Overturned SAR cases to be reassigned
  config/state_machine/configs/00_moj/20_sar/20_sar_standard_workflow.yml
  config/state_machine/configs/00_moj/20_sar/30_sar_trigger_workflow.yml
  config/state_machine/configs/00_moj/40_overturned_sar/20_overturned_sar_standard_workflow.yml
  config/state_machine/configs/00_moj/40_overturned_sar/30_overturned_sar_trigger_workflow.yml
  spec/factories/case/overturned_icos.rb
  spec/features/cases/foi/case_reassign_team_spec.rb
  spec/features/cases/sar/case_assigning_new_team_spec.rb
  spec/services/case_finder_service_spec.rb
  spec/state_machines/overturned_sar_event_spec.rb
  spec/state_machines/sar_event_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_trigger_spec.rb
  spec/support/matchers/permit_trigger_event.rb
  spec/support/standard_setup.rb
Labels: WIP

#426 CT-1853 Close page and action for Overturned SARs
  app/controllers/cases_controller.rb
  app/decorators/case/overturned_ico/sar_decorator.rb
  app/models/case/overturned_ico/sar.rb
  app/models/case/sar.rb
  app/validators/closed_case_validator.rb
  app/views/cases/overturned_sar/_close_form.html.slim
  config/locales/en.yml
  spec/controllers/cases_controller/close_spec.rb
  tmp/parallel_runtime_rspec.log
Labels: Ready for Peer Review

#434 CT-1922 Copy ICO office name from original appeal
  app/models/case/overturned_ico/base.rb
  app/services/create_overturned_ico_case_service.rb
  spec/factories/case/overturned_icos.rb
  spec/models/case/overturned_ico/base_spec.rb
  spec/models/case/overturned_ico/sar_spec.rb
  spec/services/create_overturned_ico_case_service_spec.rb
Labels: Ready for Peer Review

#435 CT-1919 Case::Base subtypes specify which state machine config to use
  app/models/case/base.rb
  app/models/case/overturned_ico/sar.rb
  app/models/concerns/case_states.rb
  config/state_machine/configs/00_moj/00_preamble.yml
  config/state_machine/configs/00_moj/20_sar/20_sar_standard_workflow.yml
  config/state_machine/configs/00_moj/20_sar/30_sar_trigger_workflow.yml
  config/state_machine/configs/00_moj/40_overturned_sar/10_overturned_sar_preamble.yml
  config/state_machine/configs/00_moj/40_overturned_sar/15_workflows_header.yml
  config/state_machine/configs/00_moj/40_overturned_sar/20_overturned_sar_standard_workflow.yml
  config/state_machine/configs/00_moj/40_overturned_sar/30_overturned_sar_trigger_workflow.yml
  spec/state_machines/workflows/sar_permitted_events/sar_trigger_spec.rb
  spec/support/features/steps/cases/responding_steps.rb
  spec/support/standard_setup.rb
Labels: Ready for Peer Review

#407 Ct 1785 edit ico closure
  app/controllers/cases_controller.rb
  app/controllers/concerns/ico_cases_params.rb
  app/views/cases/ico/_close_form.html.slim
  config/state_machine/configs/00_moj/30_ico/20_ico_trigger_workflow.yml
  spec/controllers/cases_controller/update_closure_spec.rb
  spec/features/cases/ico/editing_case_closure_spec.rb
  spec/site_prism/page_objects/pages/cases/close_page.rb
  spec/state_machines/workflows/ico_permitted_events_spec/ico_appeal_trigger_spec.rb
  spec/support/features/steps/cases/edit_steps.rb
Labels: 1st Up

#412 CT-1851 add assign overturned feature spec
  spec/factories/case/overturned_icos.rb
  spec/features/cases/overturned_sar/assigning_spec.rb
Labels: Ready for Peer Review

#439 Ct 1892 reassign unassigned case
  app/services/team_finder_service.rb
  app/services/user_reassignment_service.rb
  spec/services/user_reassignment_service_spec.rb
Labels: Ready for Peer Review

#438 CT-1893 create error if draft after final deadline
  app/models/case/ico/base.rb
  app/views/admin/cases/ico/_new.html.slim
  lib/cts/cases/create.rb
  spec/features/cases/ico/case_creating/invalid_params_spec.rb
  spec/features/cases/ico/upload_response_spec.rb
  spec/models/case/ico/base_spec.rb
  spec/site_prism/page_objects/pages/cases/new/ico_page.rb
  spec/site_prism/page_objects/sections/errors_section.rb
  spec/state_machines/workflows/ico_permitted_events_spec/ico_appeal_trigger_spec.rb
Labels: Ready for Peer Review

#454 CT-1898 add overturned foi where overturned sar is
  app/controllers/cases_controller.rb
  app/decorators/case/overturned_ico/base_decorator.rb
  app/decorators/case/overturned_ico/foi_decorator.rb
  app/decorators/case/overturned_ico/sar_decorator.rb
  app/models/case/overturned_ico/foi.rb
  app/models/correspondence_type.rb
  app/services/case_create_service.rb
  app/services/get_case_class_from_params_service.rb
  app/validators/case_link_type_validator.rb
  app/validators/closed_case_validator.rb
  config/locales/en.yml
  config/settings.yml
  db/data_migrations/20180919152312_add_overturned_foi_correspondence_type.rb
  db/structure.sql
  lib/cts/cases/constants.rb
  spec/decorators/case/overturned_ico/base_decorator_spec.rb
  spec/decorators/case/overturned_ico/foi_decorator_spec.rb
  spec/decorators/case/overturned_ico/sar_decorator_spec.rb
  spec/factories/correspondence_types.rb
  spec/models/case/overturned_ico/foi_spec.rb
  spec/validators/case_link_type_validator_spec.rb
Labels: Ready for Peer Review

#452 CT-1934 enable ot SARs on staging
  config/settings.yml
Labels: Ready for Peer Review

#455 Ct 1899 allow teams ot foi
  app/models/user.rb
  app/views/teams/_form.html.slim
  db/data_migrations/20180920110214_set_show_on_menu_false_for_overturned_fois.rb
  lib/cts/cases/constants.rb
  spec/models/correspondence_type_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: Ready for Peer Review

#459 CT-1932 admin for ot fois
  app/controllers/admin/cases_controller.rb
  app/views/admin/cases/overturned_foi/_new.html.slim
  app/views/cases/overturned_foi/_case_details.html.slim
  lib/cts/cases/constants.rb
  lib/cts/cases/create.rb
  spec/features/admin/cases/create_overturned_foi_spec.rb
  spec/site_prism/page_objects/pages/admin/cases/new_overturned_foi_page.rb
  spec/site_prism/page_objects/pages/application.rb
Labels: Ready for Peer Review

#474 CT-1943 fix missing pundit translations
  config/locales/en.yml
Labels: Ready for Peer Review

#473 CT-1939 Better case creation messages
  app/services/case_create_service.rb
  spec/controllers/cases_controller/create_spec.rb
Labels: Ready for Peer Review

#472 CT-1909 test uploading drafts ot fois
  spec/features/cases/overturned_foi/upload_response_spec.rb
Labels: ready to merge

#480 CT-1947 adds a hr between actions as per design
  app/views/cases/show.html.slim
Labels: ready to merge
