Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2018-06, with the labels that each got.

#221 CT-1405 Restrict responders to seeing closed cases processed by their…
  app/services/case_finder_service.rb
  spec/features/cases/list_filter_journey_spec.rb
Labels: in progress

#222 BUGFIX - limit scope of responder users ONLY if they are not also app…
  app/models/user.rb
  app/services/case_finder_service.rb
  spec/models/user_spec.rb
Labels: in progress

#219 CT-1404 add feature tests for deleting SAR cases
  spec/features/cases/sar/case_deleting_spec.rb
  spec/site_prism/page_objects/pages/cases/show_page.rb
  spec/support/features/steps/cases/delete_steps.rb
Labels: in progress

#226 CT-1739 fix up button text and don't set tmm to no when closing
  app/assets/stylesheets/moj/_typography.scss
  app/decorators/case/sar_decorator.rb
  app/views/cases/close.html.slim
  app/views/cases/edit_closure.html.slim
  app/views/cases/foi/_close_form.html.slim
  app/views/cases/sar/_close_form.html.slim
  config/locales/en.yml
  spec/features/cases/sar/editing_closure_details_spec.rb
  spec/helpers/cases_helper_spec.rb
  spec/support/features/steps/cases/edit_steps.rb
  spec/support/features/steps/cases/responding_steps.rb
  spec/views/cases/close_html_slim_spec.rb
  spec/views/cases/edit_closure_html_slim_spec.rb
  spec/views/cases/sar/_close_form_html_slim_spec.rb
Labels: in progress

#227 CT-1741 press and private officers are now in CorrespondenceType
  app/models/case/base.rb
  app/models/correspondence_type.rb
  app/services/default_team_service.rb
  config/settings.yml
  db/seeders/case_closure_metadata_seeder.rb
  db/seeders/dev_user_seeder.rb
  db/seeders/report_type_seeder.rb
  spec/controllers/cases_controller/show_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/factories/correspondence_types.rb
  spec/factories/users.rb
  spec/features/cases/foi/case_approvals/press_office_approvals_spec.rb
  spec/features/cases/foi/case_approvals/private_office_approvals_spec.rb
  spec/features/user_journeys/foi/compliance_review_trigger_e2e_spec.rb
  spec/features/user_journeys/foi/state_machines_and_workflows_spec.rb
  spec/features/user_journeys/foi/trigger_e2e_spec.rb
  spec/models/correspondence_type_spec.rb
  spec/services/case_unaccept_approver_assignment_service_spec.rb
  spec/services/default_team_service_spec.rb
Labels: in progress

#230 Use pluck not map to prevent memory spikes
  app/policies/case/base_policy.rb
Labels: in progress

#231 CT-1747 adds requester name to sar case details
  app/views/cases/sar/_case_details.html.slim
  spec/site_prism/page_objects/sections/cases/case_details_section.rb
  spec/views/cases/sar/_case_details_html_slim_spec.rb
Labels: Approved, in progress

#237 Ct 1345 reassign closed foi
  app/decorators/case_transition_decorator.rb
  app/services/assign_new_team_service.rb
  config/state_machine/moj.yml
  spec/features/cases/foi/case_closing_spec.rb
  spec/features/cases/sar/case_assigning_new_team_spec.rb
  spec/services/assign_new_team_service_spec.rb
  spec/state_machines/foi_event_spec.rb
  spec/state_machines/workflows/foi_permitted_events/full_approval_spec.rb
  spec/state_machines/workflows/foi_permitted_events/standard_spec.rb
  spec/state_machines/workflows/foi_permitted_events/trigger_spec.rb
Labels: Ready for Peer Review, in progress

#244 Removes CoffeeScript
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: in progress

#245 CT-1751 Updates to Create SAR page
  app/controllers/cases_controller.rb
  app/decorators/case/sar_decorator.rb
  app/models/case/sar.rb
  app/views/cases/sar/_case_details.html.slim
  app/views/cases/sar/_new.html.slim
  app/views/cases/sar/_new_form_common.html.slim
  app/views/cases/sar/_subject_type.html.slim
  app/views/cases/sar/_third_party.html.slim
  app/views/cases/sar/_third_party_relationship.html.slim
  config/locales/en.yml
  config/settings.yml
  spec/controllers/cases_controller/update_case_spec.rb
  spec/factories/case/sars.rb
  spec/models/case/sar_spec.rb
  spec/site_prism/page_objects/pages/cases/new/sar_page.rb
  spec/views/cases/sar/_case_details_html_slim_spec.rb
Labels: Ready for Peer Review, in progress

#248 CT-1766 Make Business unit columns depend on parameter in Business Un…
  app/services/stats/r003_business_unit_performance_report.rb
  spec/services/stats/r003_business_unit_performance_report_spec.rb
Labels: in progress

#249 Ct 1752 sar trigger journey
  app/policies/case/sar_policy.rb
  app/services/current_team_and_user/sar/trigger.rb
  app/views/admin/cases/sar/_new.html.slim
  app/views/cases/sar/_new_form_common.html.slim
  config/state_machine/moj.yml
  db/migrate/20180125100559_add_r006_to_report_types.rb
  db/seeders/report_type_seeder.rb
  db/structure.sql
  lib/cts/cases/constants.rb
  lib/cts/cases/create.rb
  spec/factories/case/sars.rb
  spec/features/admin/cases/adding_cases_spec.rb
  spec/features/cases/sar/case_creating/creating_spec.rb
  spec/site_prism/page_objects/pages/admin/cases/new_sar_page.rb
  spec/site_prism/page_objects/pages/cases/new/sar_page.rb
  spec/state_machines/workflows/sar_permitted_events/sar_standard_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_trigger_spec.rb
  spec/support/features/steps/cases/create_steps.rb
Labels: in progress

#258 CT-1722 Refactor SAR close to respond_and_close
  app/controllers/cases_controller.rb
  app/helpers/cases_helper.rb
  app/models/case/sar.rb
  app/policies/case/sar_policy.rb
  app/views/cases/close.html.slim
  app/views/cases/foi/_close_form.html.slim
  app/views/cases/sar/_close_form.html.slim
  app/views/cases/show.html.slim
  config/routes.rb
  config/state_machine/moj.yml
  db/structure.sql
  spec/controllers/cases_controller_spec.rb
  spec/factories/case/sars.rb
  spec/state_machines/workflows/sar_permitted_events/sar_standard_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_trigger_spec.rb
  spec/views/cases/close_html_slim_spec.rb
  spec/views/cases/sar/_close_form_html_slim_spec.rb
Labels: Ready for Peer Review

#250 CT-1298 edit foi case closure reasons
  app/assets/javascripts/modules/CaseClosure.js
  app/controllers/cases_controller.rb
  app/models/case/base.rb
  app/models/case_closure/metadatum.rb
  app/state_machines/workflows/predicates.rb
  app/validators/closed_case_validator.rb
  app/views/cases/_exemption_checkbox_section.html.slim
  app/views/cases/foi/_case_details.html.slim
  app/views/cases/foi/_close_form.html.slim
  app/views/cases/sar/_case_details.html.slim
  config/locales/en.yml
  config/state_machine/moj.yml
  lib/cts/cases/create.rb
  spec/controllers/cases_controller/process_foi_closure_params_spec.rb
  spec/controllers/cases_controller/update_closure_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/factories/case/fois.rb
  spec/features/cases/foi/case_closing_spec.rb
  spec/features/cases/foi/editing_case_closure_spec.rb
  spec/features/cases/sar/editing_closure_details_spec.rb
  spec/models/case/base_spec.rb
  spec/site_prism/page_objects/pages/cases/close_page.rb
  spec/site_prism/page_objects/pages/cases/edit_closure_page.rb
  spec/state_machines/foi_event_spec.rb
  spec/state_machines/workflows/foi_permitted_events/full_approval_spec.rb
  spec/state_machines/workflows/foi_permitted_events/standard_spec.rb
  spec/state_machines/workflows/foi_permitted_events/trigger_spec.rb
  spec/support/features/steps/cases/edit_steps.rb
  spec/support/standard_setup.rb
Labels: Ready for Peer Review

#259 Refactor FactoryGirl to FactoryBot
  Gemfile
  Gemfile.lock
  lib/cts/demo_setup.rb
  lib/tasks/cases.rake
  spec/factories/assignments.rb
  spec/factories/business_groups.rb
  spec/factories/business_units.rb
  spec/factories/case/fois.rb
  spec/factories/case/sars.rb
  spec/factories/case_attachments.rb
  spec/factories/case_closure_metadata.rb
  spec/factories/case_transitions.rb
  spec/factories/correspondence_types.rb
  spec/factories/directorates.rb
  spec/factories/feedback.rb
  spec/factories/foi_compliance_reviews.rb
  spec/factories/foi_timeliness_reviews.rb
  spec/factories/report_types.rb
  spec/factories/reports.rb
  spec/factories/search_queries.rb
  spec/factories/team_correspondence_type_roles.rb
  spec/factories/team_properties.rb
  spec/factories/teams.rb
  spec/factories/teams_users_role.rb
  spec/factories/users.rb
  spec/rails_helper.rb
  spec/site_prism/page_objects/pages/admin/cases/new_sar_page.rb
  spec/site_prism/page_objects/pages/cases/new/foi_page.rb
  spec/site_prism/page_objects/pages/cases/new/sar_page.rb
  spec/site_prism/page_objects/pages/cases/new_case_link_page.rb
  spec/support/find_or_create_strategy.rb
  spec/support/standard_setup.rb
Labels: Ready for Peer Review

#266 CT-1774 Fix bug in Assigned To filter
  app/assets/javascripts/modules/AssignedToFilter.js
Labels: Next Up!

#265 CT-1755 clear trigger NO sar
  app/controllers/cases_controller.rb
  app/views/cases/approve_response_interstitial.html.slim
  config/locales/en.yml
  config/state_machine/moj.yml
  spec/controllers/cases_controller/execute_response_approval_spec.rb
  spec/controllers/cases_controller/progress_for_clearance_spec.rb
  spec/factories/case/sars.rb
  spec/factories/case_transitions.rb
  spec/features/cases/foi/case_approvals/disclosure_specialist_approval_spec.rb
  spec/features/cases/sar/case_approval.rb/sar_approval_spec.rb
  spec/features/cases/sar/case_approval_spec.rb
  spec/features/user_journeys/sar/trigger_spec.rb
  spec/site_prism/page_objects/sections/cases/case_request_section.rb
  spec/state_machines/configurable_state_machine/manager_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_trigger_spec.rb
  spec/support/features/steps/cases/approval_steps.rb
  spec/support/features/steps/cases/taking_on_and_escalating_case_steps.rb
Labels: Next Up!

#268 CT-1791 add filter for sar cases
  app/models/case/base.rb
  app/models/correspondence_type.rb
  app/services/case_type_filter.rb
  app/views/cases/_exemption_checkbox_section.html.slim
  app/views/cases/search_filters/_case_types.html.slim
  config/locales/en.yml
  spec/features/cases/list_filter_journey_spec.rb
  spec/features/cases/sar/case_filtering_spec.rb
  spec/features/cases/search_filter_journeys_spec.rb
  spec/models/case/base_spec.rb
  spec/models/correspondence_type_spec.rb
  spec/rails_helper.rb
  spec/services/case_type_filter_spec.rb
  spec/site_prism/page_objects/sections/cases/type_filter_panel_section.rb
  spec/support/features/steps/cases/filter_steps.rb
  spec/support/view_spec_helpers.rb
  spec/views/cases/search_html_slim_spec.rb
  spec/views/teams/index_html_slim_spec.rb
Labels: Next Up!

#280 CT-1793 Add SAR Monthly report
  app/services/stats/base_monthly_performance_report.rb
  app/services/stats/case_analyser.rb
  app/services/stats/r005_monthly_performance_report.rb
  app/services/stats/r105_sar_monthly_performance_report.rb
  app/views/stats/index.html.slim
  db/migrate/20180622153909_add_report105.rb
  db/structure.sql
  spec/services/stats/r003_business_unit_performance_report_spec.rb
  spec/services/stats/r005_monthly_performance_report_spec.rb
  spec/services/stats/r105_sar_monthly_performance_report_spec.rb
  spec/support/features/steps/cases/taking_on_and_escalating_case_steps.rb
Labels: Next Up!

#274 CT-1775 Set up ICO classes
  app/controllers/cases_controller.rb
  app/decorators/case/ico/foi_decorator.rb
  app/decorators/case/ico/sar_decorator.rb
  app/models/case/base.rb
  app/models/case/ico/base.rb
  app/models/case/ico/foi.rb
  app/models/case/ico/sar.rb
  app/models/concerns/case_states.rb
  app/models/correspondence_type.rb
  app/policies/case/base_policy.rb
  app/policies/case/foi/standard_policy.rb
  app/policies/case/ico/base_policy.rb
  app/policies/case/ico/foi_policy.rb
  app/policies/case/ico/sar_policy.rb
  app/policies/case/sar_policy.rb
  app/services/case_create_service.rb
  app/services/current_team_and_user/ico/foi.rb
  app/services/current_team_and_user/ico/sar.rb
  app/views/cases/ico/_new.html.slim
  config/settings.yml
  config/state_machine/moj.yml
  db/migrate/20180620135756_add_ico_to_correspondence_types.rb
  db/seeders/correspondence_type_seeder.rb
  db/structure.sql
  spec/controllers/cases_controller/new_spec.rb
  spec/controllers/cases_controller/permitted_correspondence_types_spec.rb
  spec/factories/business_units.rb
  spec/factories/case/ico_fois.rb
  spec/factories/case/ico_sars.rb
  spec/factories/correspondence_types.rb
  spec/factory_specs/business_unit_factory_spec.rb
  spec/features/user_journeys/sar/trigger_spec.rb
  spec/models/case/base_spec.rb
  spec/models/case/foi/compliance_review_spec.rb
  spec/models/case/foi/timeliness_review_spec.rb
  spec/models/case/foi_spec.rb
  spec/models/case/ico/base_spec.rb
  spec/models/case/sar_spec.rb
  spec/models/correspondence_type_spec.rb
  spec/policies/base_policy_scope_spec.rb
  spec/rails_helper.rb
  spec/support/features/steps/cases/taking_on_and_escalating_case_steps.rb
Labels: 1st Up!

#281 CT-1325 allow add message to case on closed fois
  config/state_machine/moj.yml
  spec/state_machines/foi_event_spec.rb
  spec/state_machines/workflows/foi_permitted_events/full_approval_spec.rb
  spec/state_machines/workflows/foi_permitted_events/standard_spec.rb
  spec/state_machines/workflows/foi_permitted_events/trigger_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_standard_spec.rb
  spec/state_machines/workflows/sar_permitted_events/sar_trigger_spec.rb
Labels: 2nd Up!

#290 CT-1325 move add message out of policy to predicates
  app/policies/case/base_policy.rb
  app/state_machines/workflows/predicates.rb
  config/state_machine/moj.yml
  db/structure.sql
  spec/controllers/messages_controller_spec.rb
  spec/policies/cases/base_policy_spec.rb
  spec/state_machines/foi_event_spec.rb
Labels: 3rd Up!, Ready for Peer Review

#285 CT-1799 Edit close case copy change
  app/controllers/cases_controller.rb
  spec/support/features/interactions.rb
  spec/support/features/steps/cases/responding_steps.rb
Labels: 1st Up!, Ready for Peer Review

#289 CT-1334 Limit report categories to FOI and SAR
  app/controllers/stats_controller.rb
  app/models/correspondence_type.rb
  app/views/stats/custom.html.slim
  db/data_migrations/20180628100102_add_report_category_to_correspondence_type.rb
  db/structure.sql
  spec/controllers/stats_controller/custom_spec.rb
  spec/factories/correspondence_types.rb
  spec/models/correspondence_type_spec.rb
Labels: 2nd Up!
