Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2018-05, with the labels that each got.

#180 Ct 1700 travis fail
  .travis.yml
  app/services/case_search_service.rb
  spec/lib/cts/cases/cli_spec.rb
  spec/rails_helper.rb
Labels: Ready for Peer Review

#183 Ct 1670 filter by deadline
  Gemfile
  Gemfile.lock
  Procfile
  README.md
  app/assets/javascripts/modules/QuickLinks.js
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/moj/component/_quick_links.scss
  app/models/case/base.rb
  app/models/search_query.rb
  app/services/case_search_service.rb
  app/services/external_deadline_filter.rb
  app/views/cases/search.html.slim
  app/views/cases/search_filters/_final_deadline.html.slim
  config/locales/en.yml
  db/structure.sql
  spec/lib/papertrail_spec.rb
  spec/models/case/foi_spec.rb
  spec/models/case/sar_spec.rb
  spec/services/case_search_service_spec.rb
  spec/services/external_deadline_filter_spec.rb
Labels: Ready for Peer Review

#190 CT-1697 Filter feature specs
  spec/factories/foi_compliance_reviews.rb
  spec/factories/foi_timeliness_reviews.rb
  spec/features/cases/filter_journeys_spec.rb
  spec/site_prism/page_objects/pages/base.rb
  spec/site_prism/page_objects/pages/cases/search_page.rb
  spec/site_prism/page_objects/sections/cases/assigned_to_filter_panel_section.rb
  spec/site_prism/page_objects/sections/cases/exemption_filter_panel_section.rb
  spec/site_prism/page_objects/sections/cases/type_filter_panel_section.rb
  spec/support/features/interactions.rb
  spec/support/standard_setup.rb
Labels: Ready for Peer Review

#192 CT-1689 Add Type filter to All Open Cases page
  app/controllers/cases_controller.rb
  app/models/case/base.rb
  app/models/search_query.rb
  app/services/case_search_service.rb
  app/views/cases/index.html.slim
  app/views/cases/search_filters/_case_types.html.slim
  db/migrate/20180508131152_add_list_to_search_query_enums.rb
  db/structure.sql
  spec/controllers/cases_controller_spec.rb
  spec/factories/search_queries.rb
  spec/features/cases/foi/case_filtering_spec.rb
  spec/features/cases/list_filter_journey_spec.rb
  spec/features/cases/search_filter_journeys_spec.rb
  spec/models/search_query_spec.rb
  spec/services/case_search_service_spec.rb
  spec/site_prism/page_objects/pages/base.rb
  spec/site_prism/page_objects/pages/cases/open_cases_page.rb
  spec/site_prism/page_objects/pages/cases/search_page.rb
  spec/site_prism/support/helper_methods.rb
Labels: Ready for Peer Review

#193 CT-1692 display applied filters
  Gemfile
  Gemfile.lock
  app/assets/images/icons/close-ico.svg
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/moj/component/_filter_crumbs.scss
  app/controllers/cases_controller.rb
  app/models/search_query.rb
  app/services/assigned_business_unit_filter.rb
  app/services/case_search_service.rb
  app/services/case_status_filter.rb
  app/services/case_type_filter.rb
  app/services/exemption_filter.rb
  app/services/external_deadline_filter.rb
  app/services/open_case_status_filter.rb
  app/views/cases/index.html.slim
  app/views/cases/search.html.slim
  app/views/cases/search_filters/_filter_crumbs.html.slim
  config/i18n-tasks.yml
  config/locales/en.yml
  spec/controllers/cases_controller/search_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/features/cases/filters/external_deadline_spec.rb
  spec/features/cases/list_filter_journey_spec.rb
  spec/features/cases/search_filter_journeys_spec.rb
  spec/models/search_query_spec.rb
  spec/rails_helper.rb
  spec/services/assigned_business_unit_filter_spec.rb
  spec/services/case_status_filter_spec.rb
  spec/services/case_type_filter_spec.rb
  spec/services/exemption_filter_spec.rb
  spec/services/external_deadline_filter_spec.rb
  spec/services/open_case_status_filter_spec.rb
  spec/site_prism/page_objects/pages/base.rb
  spec/site_prism/page_objects/pages/cases/open_cases_page.rb
  spec/site_prism/page_objects/pages/cases/search_page.rb
  spec/site_prism/page_objects/sections/cases/assigned_to_filter_panel_section.rb
  spec/site_prism/page_objects/sections/cases/deadline_filter_panel_section.rb
  spec/site_prism/page_objects/sections/cases/exemption_filter_panel_section.rb
  spec/site_prism/page_objects/sections/cases/open_case_status_filter_panel_section.rb
  spec/site_prism/page_objects/sections/cases/status_filter_panel_section.rb
  spec/site_prism/page_objects/sections/cases/type_filter_panel_section.rb
  spec/site_prism/support/filter_methods.rb
Labels: Ready for Peer Review

#200 CT-1688 Add final deadline filter to open cases page
  app/views/cases/index.html.slim
  app/views/cases/search_filters/_final_deadline.html.slim
  spec/features/cases/filters/external_deadline_spec.rb
  spec/features/cases/list_filter_journey_spec.rb
  spec/site_prism/page_objects/pages/cases/open_cases_page.rb
Labels: Ready for Peer Review

#205 CT-1687 filter open cases by timeliness
  app/controllers/cases_controller.rb
  app/decorators/search_query_decorator.rb
  app/models/search_query.rb
  app/services/case_search_service.rb
  app/services/timeliness_filter.rb
  app/views/cases/index.html.slim
  app/views/cases/search_filters/_assigned_to.html.slim
  app/views/cases/search_filters/_timeliness.html.slim
  config/locales/en.yml
  config/routes.rb
  config/settings.yml
  db/migrate/20180517140929_remove_search_query_list_params.rb
  db/structure.sql
  spec/controllers/assignments_controller_spec.rb
  spec/controllers/cases_controller/state_filter_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/decorators/search_query_decorator_spec.rb
  spec/factories/search_queries.rb
  spec/features/cases/filters/timeliness_spec.rb
  spec/features/cases/foi/case_closing_spec.rb
  spec/features/cases/foi/case_filtering_spec.rb
  spec/features/cases/foi/case_listing/open_cases_spec.rb
  spec/features/cases/foi/case_listing/open_in_time_cases_spec.rb
  spec/features/cases/foi/case_listing/open_late_cases_spec.rb
  spec/features/cases/foi/case_listing/pagination_spec.rb
  spec/features/cases/foi/case_responding/mark_as_sent_spec.rb
  spec/features/cases/foi/editing_case_spec.rb
  spec/features/cases/foi/link_a_case_spec.rb
  spec/features/cases/list_filter_journey_spec.rb
  spec/features/cases/sar/case_viewing_spec.rb
  spec/features/cases/sar/sar_closing_spec.rb
  spec/features/cases/search_filter_journeys_spec.rb
  spec/features/common/primary_navigation_spec.rb
  spec/features/user_journeys/foi/downloading_stats_spec.rb
  spec/features/user_journeys/foi/managing_business_unit_spec.rb
  spec/models/search_query_spec.rb
  spec/routing/application_routes_spec.rb
  spec/routing/cases_routes_spec.rb
  spec/services/assigned_business_unit_filter_spec.rb
  spec/services/case_search_service_spec.rb
  spec/services/case_status_filter_spec.rb
  spec/services/case_type_filter_spec.rb
  spec/services/exemption_filter_spec.rb
  spec/services/external_deadline_filter_spec.rb
  spec/services/timeliness_filter_spec.rb
  spec/site_prism/page_objects/pages/cases/open_cases_page.rb
  spec/site_prism/page_objects/sections/cases/timeliness_filter_panel_section.rb
  spec/site_prism/support/filter_methods.rb
  spec/support/standard_setup.rb
  spec/views/cases/index_html_slim_spec.rb
Labels: Ready for Peer Review

#206 Ct 1394 close SAR as TMM
  spec/features/cases/sar/sar_closing_spec.rb
  spec/features/user_journeys/sar/non_trigger_spec.rb
  spec/site_prism/page_objects/pages/cases/close_page.rb
  spec/site_prism/page_objects/pages/cases/respond_page.rb
  spec/site_prism/support/case_type_element_selector.rb
  spec/support/features/steps/cases/responding_steps.rb
Labels: in progress

#207 CT-1515 changes sar external deadline to 30 calendar days
  db/migrate/20180522132456_update_external_time_limit_on_sar_cases.rb
  db/structure.sql
  spec/factories/correspondence_types.rb
  spec/services/deadline_calculator/calendar_days_spec.rb
Labels: in progress

#210 CT-1605 Do not show remove link cases where not allowed
  app/helpers/cases_helper.rb
  app/policies/case/base_policy.rb
  app/policies/case/sar_policy.rb
  app/views/cases/_linked_cases.html.slim
  spec/views/assignments/edit_page_spec.rb
  spec/views/cases/_linked_cases_html_slim_spec.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: Ready for Peer Review, in progress

#209 CT-1718 touch up open cases list
  .gitignore
  app/controllers/cases_controller.rb
  app/controllers/dashboard_controller.rb
  app/models/search_query.rb
  app/services/assigned_business_unit_filter.rb
  app/services/case_search_service.rb
  app/services/case_status_filter.rb
  app/services/case_type_filter.rb
  app/services/exemption_filter.rb
  app/services/external_deadline_filter.rb
  app/services/filter_param_parsers.rb
  app/services/open_case_status_filter.rb
  app/services/timeliness_filter.rb
  app/views/cases/index.html.slim
  app/views/cases/search.html.slim
  config/routes.rb
  db/migrate/20180524132031_add_default_for_search_queries_num_results.rb
  db/structure.sql
  spec/controllers/cases_controller/open_spec.rb
  spec/controllers/cases_controller/search_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/factories/search_queries.rb
  spec/features/cases/filters/assigned_business_unit_filter_spec.rb
  spec/features/cases/list_filter_journey_spec.rb
  spec/features/cases/search_filter_journeys_spec.rb
  spec/models/search_query_spec.rb
  spec/services/assigned_business_unit_filter_spec.rb
  spec/services/case_search_service_spec.rb
  spec/services/case_status_filter_spec.rb
  spec/services/case_type_filter_spec.rb
  spec/services/exemption_filter_spec.rb
  spec/services/external_deadline_filter_spec.rb
  spec/services/open_case_status_filter_spec.rb
  spec/services/timeliness_filter_spec.rb
  spec/site_prism/page_objects/pages/cases/open_cases_page.rb
  spec/site_prism/page_objects/sections/cases/open_case_status_filter_panel_section.rb
  spec/support/standard_setup.rb
  spec/views/cases/index_html_slim_spec.rb
  spec/views/cases/search_html_slim_spec.rb
Labels: Ready for Peer Review, in progress

#211 CT-1515 changes external deadline in the seeders
  db/seeders/correspondence_type_seeder.rb
  lib/tasks/sar.rake
Labels: Ready for Peer Review, in progress

#212 CT-1736 remove apt-get source "nodesource"
  Dockerfile
Labels: in progress

#216 CT-1729 display clearance info immediately for SAR cases
  app/models/case/sar.rb
  spec/features/cases/sar/case_creating/creating_spec.rb
  spec/models/case/sar_spec.rb
Labels: Ready for Peer Review, in progress

#220 CT-1405 Allow users to see closed SAR cases
  app/services/case_finder_service.rb
  app/views/cases/closed_cases.html.slim
  spec/features/cases/foi/case_listing/open_cases_spec.rb
  spec/services/case_finder_service_spec.rb
  spec/site_prism/page_objects/pages/cases/closed_cases_page.rb
Labels: in progress

#217 CT-1189 KILOs should be able to export stats
  app/policies/case/base_policy.rb
  config/settings.yml
  spec/features/user_journeys/foi/downloading_stats_spec.rb
  spec/policies/cases/base_policy_spec.rb
Labels: in progress
