Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2019-03, with the labels that each got.

#680 CT-2117 Display late responder name in stats
  app/services/csv_exporter.rb
  spec/services/csv_exporter_spec.rb
Labels: Ready to merge

#681 Ct 2105 edit late responder team
  app/controllers/cases_controller.rb
  app/views/cases/foi/_close_form.html.slim
  spec/features/cases/foi/editing_case_closure_spec.rb
  spec/site_prism/page_objects/pages/cases/close_page.rb
  spec/support/features/steps/cases/edit_steps.rb
Labels: Ready for Peer Review

#694 CT 2119 Time taken displaying incorrectly
  app/decorators/case/base_decorator.rb
  spec/decorators/case/base_decorator_spec.rb
  spec/features/cases/foi/case_closing_spec.rb
  spec/features/cases/overturned_foi/case_closing_spec.rb
  spec/support/features/steps/cases/responding_steps.rb
  spec/views/cases/foi/_case_details_html_slim_spec.rb
  spec/views/cases/overturned_foi/_case_details_html_slim_spec.rb
  spec/views/cases/overturned_sar/_case_details_html_slim_spec.rb
Labels: Ready to merge

#696 Ct 2140 reduce csv resource usage
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/cases_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/services/case_finder_service.rb
  app/services/csv_generator.rb
  app/services/global_nav_manager.rb
  app/services/user_active_case_count_service.rb
  app/views/layouts/_global_nav.html.slim
  config/environments/development.rb
  config/environments/test.rb
  spec/controllers/cases_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/services/case_finder_service_spec.rb
  spec/services/csv_generator_spec.rb
  spec/services/global_nav_manager_spec.rb
  spec/services/user_deletion_service_spec.rb
Labels: Ready to merge

#695 Ct 2006 ico create display all errors
  app/controllers/cases_controller.rb
  app/services/case_create_service.rb
  app/services/get_case_class_from_params_service.rb
  spec/features/cases/ico/case_creating/invalid_params_spec.rb
  spec/services/get_case_class_from_params_service_spec.rb
Labels: Ready to merge

#693 Ct 2110 show case extensions in download export
  .rubocop.yml
  app/models/case/foi/standard.rb
  app/services/csv_exporter.rb
  spec/services/csv_exporter_spec.rb
Labels: Ready to merge

#687 Add active user count to user admin page
  app/controllers/admin/users_controller.rb
  app/views/admin/users/index.html.slim
  spec/site_prism/page_objects/pages/users/index_page.rb
  spec/views/admin/users/index_html_slim_spec.rb
Labels: Ready to merge

#684 Ct 2075 edit draft timeliness
  app/controllers/concerns/foi_cases_params.rb
  app/controllers/concerns/ico_cases_params.rb
  app/controllers/concerns/sar_cases_params.rb
  app/models/case/base.rb
  app/views/cases/foi/_edit_form_details.html.slim
  app/views/cases/ico/_form.html.slim
  app/views/cases/sar/_new_form_common.html.slim
  config/locales/en.yml
  spec/controllers/cases_controller/update_case_spec.rb
  spec/factories/case/fois.rb
  spec/factories/case/ico_fois.rb
  spec/factories/case/overturned_ico_fois.rb
  spec/factories/case/overturned_ico_sars.rb
  spec/factories/case/sars.rb
  spec/features/cases/foi/editing_case_closure_spec.rb
  spec/site_prism/page_objects/sections/cases/foi_edit_details_section.rb
  spec/site_prism/page_objects/sections/cases/ico/form_section.rb
  spec/site_prism/page_objects/sections/cases/sar_edit_details_section.rb
  spec/views/cases/foi/edit_html_slim_spec.rb
  spec/views/cases/ico/edit_html_slim_spec.rb
  spec/views/cases/sar/edit_html_slim_spec.rb
Labels: Ready to merge

#618 Ct 2076 add draft timeliness to csv
  app/services/csv_exporter.rb
  spec/services/csv_exporter_spec.rb
  spec/views/users/show_html_slim_spec.rb
Labels: Approved, Ready to merge

#705 CT-2147 use extension count to decide if case has been extended
  app/models/case/foi/standard.rb
  app/services/csv_exporter.rb
  spec/services/csv_exporter_spec.rb
Labels: Ready for Peer Review

#711 Ct 2150 multi role user unable to post to trigger cases
  app/controllers/messages_controller.rb
  spec/controllers/messages_controller_spec.rb
  spec/factories/users.rb
Labels: Ready to merge

#706 Ct 2110 fix incorrect SAR removal event name
  app/models/case_transition.rb
  app/services/csv_exporter.rb
  spec/services/csv_exporter_spec.rb
Labels: Ready to merge

#710 CT-2152 Add Circle CI config file with branch build whitelist
  .circleci/config.yml
Labels: Ready to merge

#715 CT-2149 Spelling error on case edit
  config/locales/page_titles.en.yml
Labels: Ready to merge

#692 Ct 2112 download deleted cases
  app/controllers/cases_controller.rb
  app/models/case/base.rb
  app/policies/case/base_policy.rb
  app/policies/case/foi/internal_review_policy.rb
  app/policies/case/foi/standard_policy.rb
  app/policies/case/ico/foi_policy.rb
  app/policies/case/ico/sar_policy.rb
  app/policies/case/sar_policy.rb
  app/services/case_deletion_service.rb
  app/views/cases/closed_cases.html.slim
  app/views/cases/confirm_destroy.html.slim
  config/routes.rb
  db/migrate/20190228142249_add_deletion_reason_to_case.rb
  db/structure.sql
  spec/controllers/cases_controller/destroy_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/factories/case/fois.rb
  spec/factories/case/sars.rb
  spec/models/case/base_spec.rb
  spec/models/linked_case_spec.rb
  spec/policies/base_policy_scope_spec.rb
  spec/routing/cases_routes_spec.rb
  spec/services/case_deletion_service_spec.rb
  spec/site_prism/page_objects/pages/cases/closed_cases_page.rb
  spec/site_prism/page_objects/pages/cases/confirm_destroy_page.rb
  spec/support/features/steps/cases/delete_steps.rb
  spec/views/cases/closed_cases_html_slim_spec.rb
  spec/views/cases/confirm_destroy_html_slim_spec.rb
Labels: Ready to merge

#716 CT-2141 Removed last vestiges of DACU from front end
  config/locales/en.yml
Labels: Ready to merge

#701 Ct 2144 remove nplusone query issues
  app/controllers/assignments_controller.rb
  app/controllers/cases_controller.rb
  app/models/assignment.rb
  app/models/case/base.rb
  app/models/case_attachment.rb
  app/models/case_transition.rb
  app/models/correspondence_type.rb
  app/models/team.rb
  app/models/user.rb
  app/services/case_assign_responder_service.rb
  app/services/case_create_service.rb
  app/services/case_search_service.rb
  app/services/stats/audit.rb
  app/services/stats/base_appeals_performance_report.rb
  app/services/stats/base_business_unit_performance_report.rb
  app/services/stats/base_monthly_performance_report.rb
  app/services/stats/case_selector.rb
  app/services/stats/r002_appeals_performance_report.rb
  app/services/stats/r003_business_unit_performance_report.rb
  app/services/stats/r102_sar_appeals_performance_report.rb
  config/environments/test.rb
  lib/cts/cases/create.rb
  log/parallel_runtime_rspec.log
  spec/controllers/cases_controller/show_spec.rb
  spec/controllers/cases_controller_spec.rb
  spec/features/cases/foi/case_approvals/press_office_approvals_spec.rb
  spec/features/cases/foi/case_creating/creating_spec.rb
  spec/features/cases/sar/case_assigning_new_team_spec.rb
  spec/features/cases/search_filter_journeys_spec.rb
  spec/features/user_journeys/foi/compliance_review_non_trigger_e2e_spec.rb
  spec/features/user_journeys/overturned_foi/ovt_foi_trigger_e2e_spec.rb
  spec/features/user_journeys/sar/trigger_spec.rb
  spec/models/assignment_spec.rb
  spec/models/case/base_spec.rb
  spec/models/case/scopes_spec.rb
  spec/models/correspondence_type_spec.rb
  spec/services/stats/case_selector_spec.rb
Labels: Ready to merge

#702 CT-2114 remove scheduled jobs, download report now runs immediately
  Gemfile
  Gemfile.lock
  app/controllers/stats_controller.rb
  app/jobs/report_generator_job.rb
  app/models/report.rb
  config/sidekiq-background-jobs.yml
  spec/controllers/stats_controller/download_spec.rb
  spec/jobs/report_generator_job_spec.rb
Labels: Ready to merge

#723 CT-2112 added deletion reason to CSV output
  app/services/csv_exporter.rb
  spec/services/csv_exporter_spec.rb
Labels: Ready to merge

#709 CT-2124 Save case creator
  app/controllers/admin/cases_controller.rb
  app/decorators/case/base_decorator.rb
  app/models/case/base.rb
  app/models/user.rb
  app/services/case_create_service.rb
  app/services/csv_exporter.rb
  app/services/s3_uploader.rb
  config/application.rb
  config/locales/en.yml
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  db/migrate/20190228142249_add_deletion_reason_to_case.rb
  db/migrate/20190312104101_add_user_to_case.rb
  db/migrate/20190325082640_fix_reason_for_deletion.rb
  db/structure.sql
  lib/cts/cases/cli.rb
  lib/cts/cases/create.rb
  spec/factories/case/fois.rb
  spec/factories/case/ico_fois.rb
  spec/factories/case/ico_sars.rb
  spec/factories/case/overturned_ico_sars.rb
  spec/factories/case/sars.rb
  spec/features/cases/foi/case_approvals/private_office_approvals_spec.rb
  spec/features/cases/sar/case_viewing_spec.rb
  spec/lib/cts/cases/cli_spec.rb
  spec/lib/cts/cases/create_spec.rb
  spec/lib/papertrail_spec.rb
  spec/models/case/base_spec.rb
  spec/models/case/ico/foi_spec.rb
  spec/models/case/overturned_ico/foi_spec.rb
  spec/models/case/overturned_ico/sar_spec.rb
  spec/models/case/sar_spec.rb
  spec/models/case_extensions_spec.rb
  spec/services/case_approval_service_spec.rb
  spec/services/csv_exporter_spec.rb
  spec/services/response_uploader_service_spec.rb
  spec/state_machines/workflows/foi_permitted_events/full_approval_spec.rb
  spec/state_machines/workflows/overturned_foi_permitted_events/full_approval_spec.rb
  spec/support/db_housekeeping.rb
Labels: Ready to merge

#724 CT-2112 remove default deletion reason from migration
  db/migrate/20190325082640_fix_reason_for_deletion.rb
Labels: Ready for Peer Review
