Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2020-08, with the labels that each got.

#1234 CT-2989 kilo users cases view
  app/policies/case/foi/standard_policy.rb
  spec/features/cases/overturned_foi/accept_and_reject_spec.rb
  spec/policies/base_policy_scope_spec.rb
Labels: Ready to merge

#1188 Dependabot updates July 2020
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/services/bypass_params_manager.rb
  app/services/next_step_info.rb
  app/services/stats/stats_collector.rb
  app/state_machines/configurable_state_machine/machine.rb
  lib/cts/cases/create.rb
  lib/cts/policies.rb
  lib/cts/teams/cli.rb
  spec/services/stats/r003_business_unit_performance_report_spec.rb
  spec/support/case_printer.rb
  spec/support/features/steps/cases/edit_steps.rb
  spec/support/standard_setup.rb
Labels: Ready for Peer Review

#1225 Update Notify key for QA to send live emails
  config/kubernetes/qa/secrets.yaml
Labels: Ready to merge

#1226 Add guard clause to ensure dev users can't be seeded to prod environments
  db/seeders/dev_user_seeder.rb
Labels: Ready to merge

#1235 CT-2966 Use pre tag and tidy style
  app/assets/stylesheets/moj/_layout.scss
  app/views/cases/offender_sar/_subject_details.html.slim
  app/views/cases/offender_sar/_third_party_details.html.slim
Labels: Ready to merge

#1223 CT-2983 case detail visual changes
  app/views/cases/ico/_case_details.html.slim
  app/views/cases/offender_sar/_subject_details.html.slim
  app/views/cases/shared/_case_deadlines.html.slim
  app/views/cases/shared/_responding_team.html.slim
  config/locales/en.yml
  spec/site_prism/page_objects/sections/cases/case_details_section.rb
  spec/site_prism/page_objects/sections/cases/ico/case_details_section.rb
  spec/site_prism/page_objects/sections/cases/offender_sar/case_details_section.rb
  spec/site_prism/page_objects/sections/cases/overturned_foi/case_details_section.rb
  spec/site_prism/page_objects/sections/cases/overturned_sar/case_details_section.rb
Labels: Ready to merge

#1228 CT2935, CT-2936, CT-2970 & CT-2981 Letter template amendments
  app/helpers/cases_helper.rb
  app/models/letter.rb
  app/state_machines/configurable_state_machine/config_validator.rb
  app/state_machines/configurable_state_machine/machine.rb
  app/views/cases/letters/show.html.slim
  db/seeders/letter_template_seeder.rb
  db/structure.sql
  lib/assets/ims001.docx
Labels: Ready to merge

#1215 CT-2512 Open cases report for offender sar
  app/controllers/admin/cases_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cases/filters_controller.rb
  app/controllers/cases/searches_controller.rb
  app/controllers/concerns/available_case_reports.rb
  app/controllers/users_controller.rb
  app/helpers/cases_helper.rb
  app/models/case/sar/offender.rb
  app/policies/report_type_policy.rb
  app/services/csv_exporter.rb
  app/services/csv_generator.rb
  app/services/stats/r900_cases_report.rb
  app/services/stats/r901_offender_sar_cases_report.rb
  app/views/cases/shared/_case_list.html.slim
  db/data_migrations/20200725112926_add_open_cases_reports.rb
  spec/factories/report_types.rb
  spec/helpers/cases_helper_spec.rb
  spec/models/case/sar/offender_spec.rb
  spec/policies/report_type_policy_spec.rb
  spec/services/csv_generator_spec.rb
  spec/services/stats/r900_cases_report_spec.rb
  spec/services/stats/r901_offender_sar_cases_report_spec.rb
  spec/views/cases/searches/show_spec.rb
Labels: Ready to merge

#1244 CT-2938 change dpa from 1998 to 2018
  db/seeders/letter_template_seeder.rb
Labels: Ready to merge

#1233 CT-2932 Update search fields
  app/models/case/sar/offender.rb
  app/models/concerns/searchable.rb
  spec/features/cases/offender_sar/case_search_spec.rb
  spec/models/case/sar/offender_spec.rb
Labels: Ready to merge

#1245 CT-2963 Page counts data & f/e
  app/assets/stylesheets/moj/component/_case_status.scss
  app/models/case/sar/offender.rb
  app/views/cases/_case_status.html.slim
  config/locales/en.yml
  spec/site_prism/page_objects/sections/cases/case_status_section.rb
  spec/views/cases/_case_status_html_slim_spec.rb
Labels: Ready to merge

#1236 CT-2873 Changes to new data request form
  app/assets/javascripts/modules/DataRequest.js
  app/controllers/cases/data_requests_controller.rb
  app/models/data_request.rb
  app/services/data_request_create_service.rb
  app/services/data_request_update_service.rb
  app/views/cases/cover_pages/_data_requests.html.slim
  app/views/cases/data_requests/_data_request.html.slim
  app/views/cases/data_requests/edit.html.slim
  app/views/cases/data_requests/new.html.slim
  app/views/cases/offender_sar/_data_requests.html.slim
  config/locales/en.yml
  db/migrate/20200811151902_change_data_to_request_type_for_data_request.rb
  db/migrate/20200811154406_add_data_request_note_to_data_request.rb
  db/migrate/20200811222853_rename_data_request_note_to_request_type_note_for_data_request.rb
  db/migrate/20200812115318_change_request_type_column_type.rb
  db/migrate/20200812142406_add_date_range_fields_to_data_requests.rb
  db/migrate/20200819133514_add_completed_to_data_request.rb
  db/structure.sql
  spec/controllers/cases/data_requests_controller_spec.rb
  spec/factories/data_requests.rb
  spec/features/cases/offender_sar/add_data_requests_spec.rb
  spec/models/case/sar/offender_spec.rb
  spec/models/data_request_spec.rb
  spec/services/data_request_create_service_spec.rb
  spec/services/data_request_update_service_spec.rb
  spec/site_prism/page_objects/pages/cases/data_request_edit_page.rb
  spec/site_prism/page_objects/pages/cases/data_request_page.rb
  spec/site_prism/page_objects/sections/cases/data_requests_section.rb
  spec/views/cases/data_requests/edit_html_slim_spec.rb
  spec/views/cases/data_requests/new_html_slim_spec.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: Ready for Peer Review

#1246 CT-2975 Show third party name in case list
  app/helpers/cases_helper.rb
Labels: Do Not Merge

#1252 CT-2962 update exempt and final pagecounts
  app/models/case/sar/offender.rb
  app/views/cases/offender_sar/_data_requests.html.slim
  app/views/cases/offender_sar/_exempt_pages_step.html.slim
  app/views/cases/offender_sar/_pages_for_dispatch_step.html.slim
  config/locales/en.yml
  spec/features/cases/offender_sar/case_editing_spec.rb
  spec/models/case/sar/offender_spec.rb
Labels: Ready for Peer Review

#1261 CT-2973 Suppress late business unit
  app/views/cases/shared/_closed_case_details.html.slim
  spec/site_prism/page_objects/sections/cases/offender_sar/case_details_section.rb
  spec/views/cases/offender_sar/_case_details_html_slim_spec.rb
Labels: Ready for Peer Review

#1262 CT-3028 amend Time taken unit to calendar days
  config/locales/en.yml
  spec/decorators/case/offender_sar_decorator_spec.rb
  spec/features/cases/offender_sar/case_closing_spec.rb
Labels: Ready for Peer Review

#1260 CT-2958 Added additional fields to close/open report
  app/controllers/concerns/offender_sar_cases_params.rb
  app/models/case/base.rb
  app/models/case/sar/offender.rb
  app/models/warehouse/case_report.rb
  app/services/stats/etl/offender_sar_closed_cases.rb
  app/services/stats/r901_offender_sar_cases_report.rb
  app/views/cases/offender_sar/_pages_for_dispatch_step.html.slim
  config/locales/en.yml
  db/migrate/20200824130200_add_additional_columns_for_offender_sar_to_warehouse_case_reports.rb
  db/structure.sql
  spec/features/cases/offender_sar/case_editing_spec.rb
  spec/models/case/base_spec.rb
  spec/models/case/sar/offender_spec.rb
  spec/services/stats/etl/offender_sar_closed_cases_spec.rb
Labels: Ready for Peer Review

#1254 CT-2960 CT-3005 edit and data requests table
  app/assets/stylesheets/moj/_typography.scss
  app/controllers/cases/data_requests_controller.rb
  app/helpers/cases_helper.rb
  app/models/data_request.rb
  app/services/data_request_update_service.rb
  app/views/cases/data_requests/_form.html.slim
  app/views/cases/data_requests/edit.html.slim
  app/views/cases/data_requests/new.html.slim
  app/views/cases/offender_sar/_data_requests.html.slim
  config/locales/en.yml
  config/locales/event.en.yml
  db/migrate/20200819171428_drop_and_recreate_request_type_enum.rb
  db/structure.sql
  spec/controllers/cases/data_requests_controller_spec.rb
  spec/factories/data_requests.rb
  spec/features/cases/offender_sar/add_data_requests_spec.rb
  spec/features/cases/offender_sar/log_data_received_spec.rb
  spec/helpers/cases_helper_spec.rb
  spec/models/case/sar/offender_spec.rb
  spec/models/data_request_spec.rb
  spec/services/data_request_create_service_spec.rb
  spec/services/data_request_update_service_spec.rb
  spec/site_prism/page_objects/pages/cases/data_request_edit_page.rb
  spec/site_prism/page_objects/pages/cases/data_request_page.rb
  spec/site_prism/page_objects/sections/cases/data_requests_section.rb
  spec/views/cases/data_requests/edit_html_slim_spec.rb
  spec/views/cases/data_requests/new_html_slim_spec.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: Ready for Peer Review

#1271 CT-3027 non offender sars case closure in calendar days
  app/decorators/case/base_decorator.rb
  app/decorators/case/sar/offender_decorator.rb
  app/decorators/case/sar/standard_decorator.rb
  config/locales/en.yml
  spec/features/cases/sar/sar_closing_spec.rb
  spec/features/user_journeys/sar/non_trigger_spec.rb
  spec/support/features/steps/cases/responding_steps.rb
Labels: Ready to merge

#1276 Basic auth - Demo, Staging, Development
  config/kubernetes/demo/ingress.yaml
  config/kubernetes/demo/secrets.yaml
  config/kubernetes/development/ingress.yaml
  config/kubernetes/development/secrets.yaml
  config/kubernetes/staging/ingress.yaml
  config/kubernetes/staging/secrets.yaml
Labels: Ready for Peer Review

#1273 CT-3034, CT-3036 Fixed the bugs related to offender sar cases
  app/services/stats/base_monthly_performance_report.rb
  app/services/stats/etl/offender_sar_closed_cases.rb
  app/services/stats/r901_offender_sar_cases_report.rb
  config/locales/event.en.yml
  spec/services/stats/base_monthly_performance_report_spec.rb
  spec/services/stats/etl/offender_sar_closed_cases_spec.rb
Labels: Ready for Peer Review
