Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2021-02, with the labels that each got.

#1426 CT-3343 Update postgres version to 12.3
  Dockerfile
Labels: Do Not Merge, Ready for Peer Review

#1428 CT-3385 attempt to fix 2 issues for db anon
  lib/db/database_dumper.rb
  lib/db/database_loader.rb
  lib/tasks/db_dump.rake
  spec/models/report_type_spec.rb
  spec/services/stats/r901_offender_sar_cases_report_spec.rb
Labels: Ready to merge

#1453 CT-3316 CT-3317 caseworker and priority to open case report
  app/services/stats/r901_offender_sar_cases_report.rb
  spec/services/stats/r901_offender_sar_cases_report_spec.rb
Labels: Ready for Peer Review

#1452 CT-3238 Changed the open-cases reports for my-open tab for complaint
  app/views/cases/filters/index.html.slim
Labels: Ready for Peer Review

#1440 CT-3406-fix-reopen-issues
  app/controllers/cases/offender_sar_complaint_controller.rb
  config/routes.rb
  spec/features/cases/offender_sar_complaint/case_progressing_spec.rb
Labels: Ready for Peer Review

#1451 CT-3255 closure detail for complaint case type
  app/controllers/cases/offender_sar_complaint_controller.rb
  app/controllers/concerns/offender_sar_complaint_cases_params.rb
  app/helpers/cases_helper.rb
  app/models/case/sar/offender_complaint.rb
  app/models/case_closure/approval_flag/ico_offender_complaint.rb
  app/models/case_closure/approval_flag/litigation_offender_complaint.rb
  app/models/case_closure/offender_complaint_outcome.rb
  app/services/stats/etl/offender_sar_complaint_closed_cases.rb
  app/state_machines/workflows/predicates.rb
  app/views/cases/offender_sar_complaint/_appeal_outcome_details.html.slim
  app/views/cases/offender_sar_complaint/_appeal_outcome_step.html.slim
  app/views/cases/offender_sar_complaint/_approval_flags_details.html.slim
  app/views/cases/offender_sar_complaint/_approval_flags_step.html.slim
  app/views/cases/offender_sar_complaint/_case_details.html.slim
  app/views/cases/offender_sar_complaint/_complaint_type_step.html.slim
  app/views/cases/offender_sar_complaint/_costs_details.html.slim
  app/views/cases/offender_sar_complaint/_costs_step.html.slim
  app/views/cases/offender_sar_complaint/_date_received_step.html.slim
  app/views/cases/offender_sar_complaint/_outcome_details.html.slim
  app/views/cases/offender_sar_complaint/_outcome_step.html.slim
  app/views/cases/shared/_closed_case_details.html.slim
  config/locales/en.yml
  config/state_machine/configs/00_moj/50_offender_sar_complaint/20_offender_sar_complaint_standard_workflow.yml
  db/data_migrations/20210201182932_add_outcome_approval_flags_for_complaint_type.rb
  db/seeders/case_closure_metadata_seeder.rb
  spec/factories/case/offender_sar_complaints.rb
  spec/factories/case_closure_metadata.rb
  spec/features/cases/offender_sar_complaint/case_editing_spec.rb
  spec/features/cases/offender_sar_complaint/case_progressing_spec.rb
  spec/models/case/sar/offender_complaint_spec.rb
  spec/models/case_closure/approval_flag/ico_offender_complaint_spec.rb
  spec/models/case_closure/approval_flag/litigation_offender_complaint_spec.rb
  spec/models/case_closure/offender_complaint_outcome_spec.rb
  spec/site_prism/page_objects/pages/application.rb
  spec/site_prism/page_objects/pages/base.rb
  spec/site_prism/page_objects/pages/cases/edit/offender_sar_complaint_page_appeal_outcome.rb
  spec/site_prism/page_objects/pages/cases/edit/offender_sar_complaint_page_approval_flags.rb
  spec/site_prism/page_objects/pages/cases/edit/offender_sar_complaint_page_costs.rb
  spec/site_prism/page_objects/pages/cases/edit/offender_sar_complaint_page_outcome.rb
  spec/site_prism/page_objects/pages/cases/show_page.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/ico_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/litigation_spec.rb
Labels: Ready for Peer Review

#1456 CT-3433 Remove the reopen feature from complaint case
  config/state_machine/configs/00_moj/50_offender_sar_complaint/20_offender_sar_complaint_standard_workflow.yml
  spec/features/cases/offender_sar_complaint/case_progressing_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/ico_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/litigation_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/standard_spec.rb
Labels: Ready for Peer Review

#1458 CT-3439s Wording changes
  app/views/cases/offender_sar_complaint/_recipient_details_step.html.slim
  app/views/cases/offender_sar_complaint/_requester_details_step.html.slim
  config/locales/en.yml
Labels: Ready for Peer Review

#1459 CT-3438 Added back link when closing complaint case
  app/views/cases/closable/close.html.slim
  spec/features/cases/offender_sar_complaint/case_closing_spec.rb
Labels: Ready for Peer Review

#1463 CT-3466 Minor wording correction for complaint case
  app/views/cases/offender_sar_complaint/_request_details_step.html.slim
  config/locales/en.yml
Labels: Ready for Peer Review

#1473 CT-3426 Added caseworker for complaint case type
  app/models/case/base.rb
  app/models/search_query.rb
  app/services/case_filter/caseworker_filter.rb
  config/locales/filters.en.yml
  spec/models/search_query_spec.rb
  spec/services/case_filter/caseworker_filter_spec.rb
Labels: Ready for Peer Review

#1474 CT-3180 Pulled the closure details for ico from linked foi for closed-cases-report
  app/decorators/case/ico/base_decorator.rb
  app/models/warehouse/case_report.rb
  app/views/cases/shared/_closed_case_details.html.slim
  spec/decorators/case/ico/base_decorator_spec.rb
  spec/models/warehouse/case_report_spec.rb
Labels: Ready for Peer Review

#1479 CT-3474 Added rake task for validating migrated complaints
  lib/tasks/complaint_cases_data.rake
Labels: Ready for Peer Review

#1478 CT-3455 Initialised the things git-secrets need and updated the Readme for the new parts
  .overcommit.yml
  Gemfile
  Gemfile.lock
  README.md
  config/git-hooks/pre-commit.sh
  config/kubernetes/demo/secrets.yaml
  config/kubernetes/development/secrets.yaml
  config/kubernetes/production/secrets.yaml
  config/kubernetes/qa/secrets.yaml
  config/kubernetes/staging/secrets.yaml
Labels: Ready for Peer Review

#1480 CT-3047 Fixed wrong report type for litigation performance report
  app/services/stats/r208_offender_litigation_complaint_monthly_performance_report.rb
  db/data_migrations/20210223152246_fix_seq_id_for_litigation_perf_report.rb
  spec/services/stats/r208_offender_litigation_complaint_monthly_performance_report_spec.rb
Labels: Ready for Peer Review
