Repository ministryofjustice/correspondence_tool_staff, pull requests merged in 2021-03, with the labels that each got.

#1483 CT-3476 A few bug fixes related to complaint and ico
  app/controllers/cases/offender_sar_complaint_controller.rb
  app/decorators/case/base_decorator.rb
  app/models/warehouse/case_report.rb
  app/services/csv_exporter.rb
  lib/tasks/complaint_cases_data.rake
  spec/features/cases/offender_sar_complaint/case_editing_spec.rb
  spec/site_prism/page_objects/pages/cases/edit/offender_sar_complaint_page_appeal_outcome.rb
  spec/site_prism/page_objects/pages/cases/edit/offender_sar_complaint_page_outcome.rb
Labels: Ready for Peer Review

#1481 CT-3473 Changed the litigation flow based on the feedback
  app/decorators/case_transition_decorator.rb
  app/helpers/cases_helper.rb
  config/locales/event.en.yml
  config/locales/state.en.yml
  config/state_machine/configs/00_moj/50_offender_sar_complaint/10_offender_sar_complaint_preamble.yml
  config/state_machine/configs/00_moj/50_offender_sar_complaint/20_offender_sar_complaint_standard_workflow.yml
  spec/factories/case/offender_sar_complaints.rb
  spec/factories/case_transitions.rb
  spec/features/cases/offender_sar_complaint/case_editing_spec.rb
  spec/features/cases/offender_sar_complaint/case_progressing_spec.rb
  spec/features/user_journeys/foi/downloading_stats_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/litigation_spec.rb
Labels: Ready for Peer Review

#1491 CT-3505 Fixed the wrong msg when no change made from user
  app/services/case_updater_service.rb
  spec/features/cases/offender_sar_complaint/case_editing_spec.rb
Labels: Ready for Peer Review

#1489 CT-3425 Add 'High' flag on case list pages for high priority complaint case
  app/decorators/case/base_decorator.rb
  app/decorators/case/sar/offender_complaint_decorator.rb
  app/views/cases/filters/index.html.slim
  app/views/cases/shared/_case_list.html.slim
  spec/decorators/case/base_decorator_spec.rb
  spec/decorators/case/offender_sar_complaint_decorator_spec.rb
Labels: Ready for Peer Review

#1488 CT-3442 Hide the data_requests button from to_be_assessed state
  app/views/cases/offender_sar/_data_requests.html.slim
  config/state_machine/configs/00_moj/50_offender_sar_complaint/20_offender_sar_complaint_standard_workflow.yml
  spec/features/cases/offender_sar_complaint/add_data_requests_spec.rb
  spec/features/cases/offender_sar_complaint/case_editing_spec.rb
  spec/features/cases/offender_sar_complaint/log_data_received_spec.rb
  spec/policies/cases/sar/offender_complaint_policy_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/ico_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/litigation_spec.rb
  spec/state_machines/workflows/offender_sar_complaint_permitted_events/standard_spec.rb
Labels: Ready for Peer Review

#1490 CT-3290 Added extra backlink and fixed the bug
  app/controllers/cases/offender_sar_complaint_controller.rb
  app/controllers/cases/offender_sar_controller.rb
  app/decorators/case/sar/offender_base_decorator.rb
  app/views/cases/offender_sar/_edit.html.slim
  app/views/cases/offender_sar/_new.html.slim
  app/views/cases/offender_sar_complaint/_appeal_outcome_step.html.slim
  app/views/cases/offender_sar_complaint/_approval_flags_step.html.slim
  app/views/cases/offender_sar_complaint/_complaint_type_step.html.slim
  app/views/cases/offender_sar_complaint/_confirm_offender_sar_step.html.slim
  app/views/cases/offender_sar_complaint/_costs_step.html.slim
  app/views/cases/offender_sar_complaint/_date_received_step.html.slim
  app/views/cases/offender_sar_complaint/_date_responded_step.html.slim
  app/views/cases/offender_sar_complaint/_edit.html.slim
  app/views/cases/offender_sar_complaint/_new.html.slim
  app/views/cases/offender_sar_complaint/_outcome_step.html.slim
  app/views/cases/offender_sar_complaint/_recipient_details_step.html.slim
  app/views/cases/offender_sar_complaint/_request_details_step.html.slim
  app/views/cases/offender_sar_complaint/_requested_info_step.html.slim
  app/views/cases/offender_sar_complaint/_requester_details_step.html.slim
  app/views/cases/offender_sar_complaint/_set_deadline_step.html.slim
  app/views/cases/offender_sar_complaint/_subject_details_step.html.slim
  spec/features/cases/offender_sar_complaint/case_creating_spec.rb
  spec/site_prism/page_objects/pages/cases/new/offender_sar_complaint_page_confirm_case.rb
Labels: Ready for Peer Review

#1482 CT-3448 upgrade ruby from 2.5 to 2.7.x
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
  app/controllers/admin/dashboard_controller.rb
  app/models/search_query.rb
  config/environments/test.rb
  spec/features/cases/foi/case_viewing/downloading_response_spec.rb
  spec/services/s3_uploader_spec.rb
  spec/services/team_move_service_spec.rb
  spec/views/cases/filters/incoming_cases_html_slim_spec.rb
Labels: Ready to merge

#1496 Ct 3308 Security fixes for Dockerfile
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
Labels: Do Not Merge

#1500 CT-3522 Changed the perf calculation in appeal reports
  app/services/stats/appeal_calculations.rb
  spec/services/stats/r002_appeals_performance_report_spec.rb
  spec/services/stats/r102_sar_appeals_performance_report_spec.rb
Labels: Ready for Peer Review

#1497 CT-2303 Added a feature of uploading the requests files
  app/controllers/cases/attachments_controller.rb
  app/controllers/concerns/case_attachment_params.rb
  app/helpers/cases_helper.rb
  app/policies/case/base_policy.rb
  app/services/request_uploader_service.rb
  app/views/cases/_case_request.html.slim
  app/views/cases/attachments/new.html.slim
  config/locales/en.yml
  config/locales/page_titles.en.yml
  config/routes.rb
  spec/features/cases/foi/editing_case_spec.rb
  spec/features/cases/sar/editing_case_spec.rb
  spec/services/request_uploader_service_spec.rb
  spec/site_prism/page_objects/pages/application.rb
  spec/site_prism/page_objects/pages/cases/upload_requests_page.rb
  spec/views/assignments/edit_page_spec.rb
  spec/views/cases/_case_request_html_slim_spec.rb
  spec/views/cases/attachments/new_html_slim_spec.rb
  spec/views/cases/show_html_slim_spec.rb
Labels: Ready to merge

#1507 CT-3520 3526 Allow London user to link ICO link to FOI IR case
  app/controllers/concerns/ico_cases_params.rb
  app/validators/case_link_type_validator.rb
  config/locales/en.yml
  lib/tasks/relink_ico_to_foi_ir.rake
  spec/controllers/cases/ico_controller_spec.rb
  spec/factories/case/fois.rb
  spec/features/cases/ico/case_creating/creating_spec.rb
  spec/services/stats/r004_cabinet_office_report_spec.rb
Labels: Ready to merge

#1508 CT-3523 Fixed the bugs when assigning responder for complaint case
  app/controllers/assignments_controller.rb
  app/services/user_reassignment_service.rb
  spec/features/cases/offender_sar_complaint/case_assign_responder_spec.rb
  spec/services/user_reassignment_service_spec.rb
Labels: Ready for Peer Review
